Repository at-sso/Budget-Tracker-WebApp, pull requests merged in 2024-04, with the labels that each got.

#2 creacion de modulo de base de datos
  data.py
Labels: enhancement, help wanted

#4 Updated backend & pull request #2 fix.
  .vscode/settings.json
  data.py
  main.py
  src/__init__.py
  src/api_handler/__init__.py
  src/api_handler/templates/index.html
  src/backend/const.py
  src/backend/database.py
  src/backend/logger.py
  src/backend/timer.py
  src/frontend/fetch_expenses.js
  src/template/index.html
Labels: enhancement

#7 Type & formatting fixes.
  .vscode/settings.json
  env/mypy.ini
  src/__init__.py
  src/backend/database.py
  src/backend/logger.py
  src/frontend/fetch_expenses.js
  src/frontend/forms/delete_form.py
  src/frontend/forms/edit_forms.py
  src/frontend/forms/expense_forms.py
  src/template/index.html
Labels: enhancement

#8 Documentation part 1, Complete
  docs/eng/_index.md
  docs/eng/api.md
  docs/eng/backend/const.md
  docs/eng/backend/database.md
  docs/eng/backend/logger.md
  docs/eng/backend/timer.md
  docs/eng/frontend/forms_init/delete.md
  docs/eng/frontend/forms_init/edit.md
  docs/eng/frontend/forms_init/expense.md
  docs/eng/frontend/how_we_fetch.md
  docs/eng/frontend/template_index.md
  docs/eng/index.md
  docs/eng/logger.md
  docs/eng/timer.md
  docs/esp/_index.md
  docs/esp/api.md
  docs/esp/logger.md
  docs/esp/timer.md
  main.py
  src/__init__.py
  src/backend/database.py
  src/backend/timer.py
  src/frontend/fetch_expenses.js
  src/frontend/forms/delete_form.py
  src/frontend/forms/edit_forms.py
  src/frontend/forms/expense_forms.py
  src/frontend/style.css
  src/template/index.html
Labels: documentation

#11 Added API
  src/frontend/external_API/currency_api.js
  src/frontend/forms/expense_forms.py
  src/template/index.html
Labels: enhancement

#12 traduccion
  docs/esp/frontend/forms_init/delete.md
  docs/esp/frontend/forms_init/edit.md
  docs/esp/frontend/how_we_fetch.md
  docs/esp/index.md
Labels: documentation

#13 Final documentation commit.
  docs/esp/backend/database.md
  docs/esp/backend/logger.md
  docs/esp/backend/timer.md
  docs/esp/frontend/forms_init/delete.md
  docs/esp/frontend/forms_init/edit.md
  docs/esp/frontend/forms_init/expense.md
  docs/esp/frontend/how_we_fetch.md
  docs/esp/frontend/template_index.md
  docs/esp/index.md
Labels: documentation
